Improve condition check. Use recommended way and check for None. I've go the following Warning in my tests with Report Lab Version: RELEASE 2.1  at 15:00 GMT  24/May/2007
raise Exception("Subprocess error: %s" % error)
Exception: Subprocess error: ...\rml\flowable.py:863: 
FutureWarning: The behavior of this method will change in future versions. 
Use specific 'len(elem)' or 'elem is not None' test instead.